name: Janitor

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  aws-janitor:
    name: aws-janitor
    runs-on:
      group: organization/Default
    container:
      image: busybox:latest
    steps:
      - run: ping -c10 10.124.138.151
